/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_mynative_NativeExample */

#ifndef _Included_org_example_mynative_NativeExample
#define _Included_org_example_mynative_NativeExample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_mynative_NativeExample
 * Method:    nativeMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_example_mynative_NativeExample_nativeMethod
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
